FROM alpine:3.14

RUN apk --update --upgrade --no-cache add \
    python3 py3-pip gcc python3-dev

WORKDIR /function
ADD requirements.txt /function/
RUN pip install --upgrade pip
RUN pip3 install --target /python/  --no-cache --no-cache-dir -r requirements.txt
ENV PYTHONPATH=/function:/python

ADD . /function/
ENTRYPOINT ["/python/bin/fdk", "/function/func.py", "handler"]
