FROM fnproject/python:3.11-dev

WORKDIR /function

ADD src/requirements.txt /function/
ADD src/func.py /function/

RUN pip3 install --target /python/  --no-cache --no-cache-dir -r requirements.txt
ENV PYTHONPATH=/function:/python

ADD . /function/
ENTRYPOINT ["/python/bin/fdk", "/function/func.py", "handler"]
