name: GraalPy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
      OCI_FUNC_OCID: ${{ secrets.OCI_FUNC_OCID }}
    steps:
    - name: Set current date as env variable
      run: echo "NOW=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV
    - name: Echo current date
      run: echo ${{ env.NOW }}
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Log into OCIR
      uses: oracle-actions/login-ocir@v1.2.1
      with:
        auth_token: ${{ secrets.OCI_AUTH_TOKEN }}
    - name: Build and Push base graalpy image
      run: |
        wget -O Dockerfile.graalpy https://github.com/graalvm/container/raw/master/graalpy-community/Dockerfile.ol8
        docker build -f Dockerfile.graalpy -t graalpy:24.0.1-ol8 --build-arg GRAALVM_VERSION=24.0.1 --build-arg GRAALVM_PKG=https://github.com/oracle/graalpython/releases/download/graal-24.0.1/graalpy-24.0.1-linux-amd64.tar.gz
    - name: Build and Push graalpyfunction
      run: |
        docker build -f Dockerfile -t fra.ocir.io/frsxwtjslf35/graalpyfunction:${{ env.NOW }} .
        docker push fra.ocir.io/frsxwtjslf35/graalpyfunction:${{ env.NOW }}
    - name: Update function
      uses: oracle-actions/run-oci-cli-command@v1.2.0
      with:
        command: "oci fn function update --function-id ${{ secrets.OCI_FUNC_OCID }} --image fra.ocir.io/frsxwtjslf35/graalpyfunction:${{ env.NOW }}"
        silent: false